#!/usr/bin/env sh

# This is a wrapper script, that automatically downloads mill from GitHub release pages
# You can give the required mill version with MILL_VERSION env variable
# If no version is given, it falls back to the value of DEFAULT_MILL_VERSION

set -e

if [ -z "${DEFAULT_MILL_VERSION}" ] ; then
  DEFAULT_MILL_VERSION="0.12.3"
fi

if [ -z "$MILL_VERSION" ] ; then
  if [ -f ".mill-version" ] ; then
    MILL_VERSION="$(head -n 1 .mill-version 2> /dev/null)"
  elif [ -f "mill" ] && [ "$0" != "mill" ] ; then
    MILL_VERSION=$(grep -F "DEFAULT_MILL_VERSION=" "mill" | head -n 1 | cut -d= -f2)
  else
    MILL_VERSION=$DEFAULT_MILL_VERSION
  fi
fi

if [ "x${XDG_CACHE_HOME}" != "x" ] ; then
  MILL_DOWNLOAD_PATH="${XDG_CACHE_HOME}/mill/download"
else
  MILL_DOWNLOAD_PATH="${HOME}/.cache/mill/download"
fi

MILL_EXEC_PATH="${MILL_DOWNLOAD_PATH}/${MILL_VERSION}"

if [ ! -x "$MILL_EXEC_PATH" ] ; then
  mkdir -p "$MILL_DOWNLOAD_PATH"
  DOWNLOAD_FILE=$MILL_EXEC_PATH-tmp-download
  MILL_VERSION_TAG=$(echo "$MILL_VERSION" | sed -E 's/([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
  MILL_DOWNLOAD_URL="https://github.com/com-lihaoyi/mill/releases/download/${MILL_VERSION_TAG}/${MILL_VERSION}-assembly"
  curl --fail -L -o "$DOWNLOAD_FILE" "$MILL_DOWNLOAD_URL"
  chmod +x "$DOWNLOAD_FILE"
  mv "$DOWNLOAD_FILE" "$MILL_EXEC_PATH"
  unset DOWNLOAD_FILE
  unset MILL_DOWNLOAD_URL
fi

unset MILL_DOWNLOAD_PATH
unset MILL_VERSION

exec "$MILL_EXEC_PATH" "$@"
